// constants/cities.js
export const CITY_DATA = [
  {
    code: 'NY',
    name: 'New York',
    country: 'United States',
    countrycode: 'US',
    continent: 'North America',
    lat: 40.7128,
    lon: -74.0060,
    timezone: 'America/New_York',
    bg: 'https://res.cloudinary.com/bradley-cdn/image/upload/v1752299685/newyork_scnwns.webp',
    landmark: 'Statue of Liberty',
    flag: '🇺🇸',
  },
  {
    code: 'SE',
    name: 'Seoul',
    country: 'South Korea',
    countrycode: 'KR',
    continent: 'Asia',
    lat: 37.5665,
    lon: 126.9780,
    timezone: 'Asia/Seoul',
    bg: 'https://res.cloudinary.com/bradley-cdn/image/upload/v1752299707/seoul_vwna7c.webp',
    landmark: 'N Seoul Tower',
    flag: '🇰🇷',
  },
  {
    code: 'TK',
    name: 'Tokyo',
    country: 'Japan',
    countrycode: 'JP',
    continent: 'Asia',
    lat: 35.6895,
    lon: 139.6917,
    timezone: 'Asia/Tokyo',
    bg: 'https://res.cloudinary.com/bradley-cdn/image/upload/v1752299660/tokyo_rfxiak.webp',
    landmark: 'Tokyo Tower',
    flag: '🇯🇵',
  },
  {
    code: 'NB',
    name: 'Nairobi',
    country: 'Kenya',
    countrycode: 'KE',
    continent: 'Africa',
    lat: -1.2921,
    lon: 36.8219,
    timezone: 'Africa/Nairobi',
    bg: 'https://res.cloudinary.com/bradley-cdn/image/upload/v1752299647/nairobi_kz0jvy.webp',
    landmark: 'KICC Tower',
    flag: '🇰🇪',
  },
  {
    code: 'BK',
    name: 'Bangkok',
    country: 'Thailand',
    countrycode: 'TH',
    continent: 'Asia',
    lat: 13.7563,
    lon: 100.5018,
    timezone: 'Asia/Bangkok',
    bg: 'https://res.cloudinary.com/bradley-cdn/image/upload/v1752299633/bangkok_bdiubk.webp',
    landmark: 'Grand Palace',
    flag: '🇹🇭',
  },
  {
    code: 'DB',
    name: 'Dubai',
    country: 'United Arab Emirates',
    countrycode: 'AE',
    continent: 'Asia',
    lat: 25.276987,
    lon: 55.296249,
    timezone: 'Asia/Dubai',
    bg: 'https://res.cloudinary.com/bradley-cdn/image/upload/v1752299672/dubai_rzoinx.webp',
    landmark: 'Burj Khalifa',
    flag: '🇦🇪',
  },
  {
    code: 'RM',
    name: 'Rome',
    country: 'Italy',
    countrycode: 'IT',
    continent: 'Europe',
    lat: 41.9028,
    lon: 12.4964,
    timezone: 'Europe/Rome',
    bg: 'https://res.cloudinary.com/bradley-cdn/image/upload/v1752299719/rome_ls1bxn.webp',
    landmark: 'Colosseum',
    flag: '🇮🇹',
  },
  {
    code: 'PR',
    name: 'Paris',
    country: 'France',
    countrycode: 'FR',
    continent: 'Europe',
    lat: 48.8566,
    lon: 2.3522,
    timezone: 'Europe/Paris',
    bg: 'https://res.cloudinary.com/bradley-cdn/image/upload/v1752299734/paris_ccfpvr.webp',
    landmark: 'Eiffel Tower',
    flag: '🇫🇷',
  },
  {
    code: 'TO',
    name: 'Toronto',
    country: 'Canada',
    countrycode: 'CA',
    continent: 'North America',
    lat: 43.651070,
    lon: -79.347015,
    timezone: 'America/Toronto',
    bg: 'https://res.cloudinary.com/bradley-cdn/image/upload/v1752299752/toronto_avf86z.webp',
    landmark: 'CN Tower',
    flag: '🇨🇦',
  },
  {
    code: 'LD',
    name: 'London',
    country: 'United Kingdom',
    countrycode: 'GB',
    continent: 'Europe',
    lat: 51.5072,
    lon: -0.1276,
    timezone: 'Europe/London',
    bg: 'https://res.cloudinary.com/bradley-cdn/image/upload/v1752299767/london_ffionl.webp',
    landmark: 'Big Ben',
    flag: '🇬🇧',
  },
]
