export const CITY_DATA = [
  {
    code: 'NY',
    name: 'New York',
    country: 'United States',
    continent: 'North America',
    lat: 40.7128,
    lon: -74.0060,
    timezone: 'America/New_York',
    bg: 'https://res.cloudinary.com/bradley-cdn/image/upload/f_auto,q_auto/v1752001468/newyork_scnwns.jpg',
    landmark: 'Statue of Liberty',
    flag: '🇺🇸',
  },
  {
    code: 'SE',
    name: 'Seoul',
    country: 'South Korea',
    continent: 'Asia',
    lat: 37.5665,
    lon: 126.9780,
    timezone: 'Asia/Seoul',
    bg: 'https://res.cloudinary.com/bradley-cdn/image/upload/f_auto,q_auto/v1751997932/seoul_vwna7c.jpg',
    landmark: 'N Seoul Tower',
    flag: '🇰🇷',
  },
  {
    code: 'TK',
    name: 'Tokyo',
    country: 'Japan',
    continent: 'Asia',
    lat: 35.6895,
    lon: 139.6917,
    timezone: 'Asia/Tokyo',
    bg: 'https://res.cloudinary.com/bradley-cdn/image/upload/f_auto,q_auto/v1751997933/tokyo_rfxiak.jpg',
    landmark: 'Tokyo Tower',
    flag: '🇯🇵',
  },
  {
    code: 'NB',
    name: 'Nairobi',
    country: 'Kenya',
    continent: 'Africa',
    lat: -1.2921,
    lon: 36.8219,
    timezone: 'Africa/Nairobi',
    bg: 'https://res.cloudinary.com/bradley-cdn/image/upload/f_auto,q_auto/v1751997934/nairobi_kz0jvy.jpg',
    landmark: 'KICC Tower',
    flag: '🇰🇪',
  },
  {
    code: 'BK',
    name: 'Bangkok',
    country: 'Thailand',
    continent: 'Asia',
    lat: 13.7563,
    lon: 100.5018,
    timezone: 'Asia/Bangkok',
    bg: 'https://res.cloudinary.com/bradley-cdn/image/upload/f_auto,q_auto/v1751997938/bangkok_bdiubk.jpg',
    landmark: 'Grand Palace',
    flag: '🇹🇭',
  },
  {
    code: 'DB',
    name: 'Dubai',
    country: 'United Arab Emirates',
    continent: 'Asia',
    lat: 25.276987,
    lon: 55.296249,
    timezone: 'Asia/Dubai',
    bg: 'https://res.cloudinary.com/bradley-cdn/image/upload/f_auto,q_auto/v1751997932/dubai_rzoinx.jpg',
    landmark: 'Burj Khalifa',
    flag: '🇦🇪',
  },
  {
    code: 'RM',
    name: 'Rome',
    country: 'Italy',
    continent: 'Europe',
    lat: 41.9028,
    lon: 12.4964,
    timezone: 'Europe/Rome',
    bg: 'https://res.cloudinary.com/bradley-cdn/image/upload/f_auto,q_auto/v1751997931/rome_ls1bxn.jpg',
    landmark: 'Colosseum',
    flag: '🇮🇹',
  },
  {
    code: 'PR',
    name: 'Paris',
    country: 'France',
    continent: 'Europe',
    lat: 48.8566,
    lon: 2.3522,
    timezone: 'Europe/Paris',
    bg: 'https://res.cloudinary.com/bradley-cdn/image/upload/f_auto,q_auto/v1751997930/paris_ccfpvr.jpg',
    landmark: 'Eiffel Tower',
    flag: '🇫🇷',
  },
  {
    code: 'TO',
    name: 'Toronto',
    country: 'Canada',
    continent: 'North America',
    lat: 43.651070,
    lon: -79.347015,
    timezone: 'America/Toronto',
    bg: 'https://res.cloudinary.com/bradley-cdn/image/upload/f_auto,q_auto/v1751997929/toronto_avf86z.jpg',
    landmark: 'CN Tower',
    flag: '🇨🇦',
  },
  {
    code: 'LD',
    name: 'London',
    country: 'United Kingdom',
    continent: 'Europe',
    lat: 51.5072,
    lon: -0.1276,
    timezone: 'Europe/London',
    bg: 'https://res.cloudinary.com/bradley-cdn/image/upload/f_auto,q_auto/v1751997928/london_ffionl.jpg',
    landmark: 'Big Ben',
    flag: '🇬🇧',
  },
]
